add vaapi support via '-p vaapi'

diff --git a/fauxstream b/fauxstream
--- a/fauxstream
+++ b/fauxstream
@@ -43,7 +43,7 @@
 #   be disabled per twich, videoberg recommendations.
 ###########
 
-USAGE="Usage: `basename $0` [-m] [-d mic_device] [-a audiooffset] [-ab audio_bitrate] [-n window_name] [-c codec] [-vb bitrate] [-r resolution] [-o offset] [-fullscreen] [-s <scale_x>:<scale_y>] [-f framerate] [-v volume_adjustment] [-vmic mic_volume] [-vmon monitor_volume] [-t threads ] [-noaudio] [-crf crf] <rtmp url>"
+USAGE="Usage: `basename $0` [-p preset] [-m] [-d mic_device] [-a audiooffset] [-ab audio_bitrate] [-n window_name] [-c codec] [-vb bitrate] [-r resolution] [-o offset] [-fullscreen] [-s <scale_x>:<scale_y>] [-f framerate] [-v volume_adjustment] [-vmic mic_volume] [-vmon monitor_volume] [-t threads ] [-noaudio] [-crf crf] <rtmp url>"
 
 audiooffset=0.0
 audio_bitrate=96
@@ -60,11 +60,16 @@ mic=0
 mic_device=snd/0
 noaudio=0
 offset=
+#preset=		# don't set $preset, so that ${#preset[*]} == 0 can be used
+preset_vaapi=
 resolution=1280x720
 scaleres=
 threads=0
 videocodec=libx264
 video_bitrate=3500
+video_device=
+video_format=
+video_output_fps=
 volume=1.0
 volume_mic=1.0
 volume_mon=1.0
@@ -99,6 +104,7 @@ do
 		-n) windowname="$2"; shift;;
 		-noaudio) noaudio=1;;
 		-o) offset="$2"; shift;;
+		-p) preset[${#preset[*]}]="$2"; shift;;
 		-r) resolution="$2"; shift;;
 		-s) scaleres="$2"; shift;;
 		-t) threads="$2"; shift;;
@@ -114,6 +120,22 @@ done
 
 if [[ -z "$filename" ]];then
 	echo $USAGE; exit 0
+fi
+
+for p in ${preset[@]}; do
+	case "$p" in
+		vaapi) preset_vaapi=1;;
+		*) echo "invalid preset specified: $p"; exit 1;;
+	esac
+done
+
+if [[ $preset_vaapi -eq 1 ]]; then
+	videocodec=h264_vaapi
+	video_device="-vaapi_device /dev/dri/renderD128"
+	video_format="-vf "format=nv12,hwupload""
+else
+	video_format="-vf "${scaleres}format=yuv420p""
+	video_output_fps= "-r $framerate"
 fi
 
 bufsize=`expr $video_bitrate \* 2`
@@ -188,12 +210,13 @@ BASE="\
 
 VIDEO="\
 -thread_queue_size 512 \
--f x11grab \
 -show_region 1 \
+${video_device} \
+-f x11grab \
 -video_size $resolution \
 -framerate $framerate \
 -i $DISPLAY$offset \
--r $framerate \
+${video_output_fps} \
 -c:v $videocodec \
 -profile:v high \
 -b:v ${video_bitrate}k \
@@ -202,10 +225,28 @@ VIDEO="\
 -bufsize ${bufsize}k \
 -preset ultrafast \
 -tune zerolatency \
--vf "${scaleres}format=yuv420p" \
+${video_format} \
 -g $gop \
 -keyint_min $framerate \
 -x264-params no-scenecut=1"
+
+VIDEO_VA="-re \
+-video_size $resolution \
+-vaapi_device /dev/dri/renderD128 \
+-f x11grab \
+-show_region 1 \
+-framerate $framerate \
+-thread_queue_size 512 \
+-i $DISPLAY$offset \
+-vf "hwupload,scale_vaapi=format=nv12,fps=fps=$framerate" \
+-c:v $videocodec \
+-b:v ${video_bitrate}k \
+-minrate ${video_bitrate}k \
+-maxrate ${video_bitrate}k \
+-bufsize ${bufsize}k \
+-preset ultrafast \
+-g $gop \
+-vsync 0"
 
 AUDIO="-c:a aac \
 -b:a ${audio_bitrate}k \
@@ -218,7 +259,7 @@ AUDIOMERGE="volume=$volume_mic,aformat=channel_layouts=stereo$hilopass[l];[1]vol
 
 if [ $noaudio -lt 1 -a $mic -lt 1 ]; then
 	#only monitoring stream
-  ffmpeg $BASE -f sndio -i snd/$sndio_device.mon $AUDIO -f nut pipe:1 | \
+	ffmpeg $BASE -f sndio -i snd/$sndio_device.mon $AUDIO -f nut pipe:1 | \
 	ffmpeg $BASE -f nut -itsoffset $audiooffset -i pipe:0 $VIDEO -c:a copy -f "${container}" "$filename"
 elif [ $noaudio -lt 1 ]; then
 	#mon + mic stream
